# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricao', models.BooleanField(verbose_name='restri\xe7\xe3o alimentar/alergia')),
                ('especificacao', models.CharField(blank=True, max_length=250, null=True, verbose_name='especifica\xe7\xe3o da restri\xe7\xe3o')),
                ('vegetariano', models.BooleanField(verbose_name='vegetariano')),
                ('vegano', models.BooleanField(verbose_name='vegano')),
                ('peixe', models.BooleanField(verbose_name='come peixe')),
                ('frango', models.BooleanField(verbose_name='come frango')),
            ],
            options={
                'verbose_name': 'informa\xe7\xe3o alimentar',
                'verbose_name_plural': 'informa\xe7\xf5es alimentares',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'cidade',
                'verbose_name_plural': 'cidades',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='nome')),
                ('fone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
            ],
            options={
                'verbose_name': 'contato de emerg\xeancia',
                'verbose_name_plural': 'contatos de emerg\xeancia',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='raz\xe3o social')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, null=True, verbose_name='inscri\xe7\xe3o estadual')),
                ('inscricao_estadual_st', models.CharField(blank=True, max_length=30, null=True, verbose_name='situa\xe7\xe3o ie')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=30, null=True, verbose_name='inscri\xe7\xe3o municipal')),
                ('tipo', models.CharField(blank=True, max_length=1, verbose_name='tipo')),
                ('data_cadastro', models.DateField(verbose_name='data de cadastro')),
                ('suframa', models.CharField(blank=True, max_length=9, null=True, verbose_name='SUFRAMA')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='email')),
                ('imagem_logotipo', models.ImageField(blank=True, upload_to=b'', verbose_name='logotipo')),
                ('crt', models.IntegerField(blank=True, null=True, verbose_name='CRT')),
                ('tipo_regime', models.CharField(blank=True, max_length=30, null=True, verbose_name='tipo de regime')),
                ('aliquota_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='al\xedquota pis')),
                ('aliquota_confins', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='al\xedquota confins')),
                ('fk_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.Empresa', verbose_name='empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100, verbose_name='logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='n\xfamero')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('principal', models.BooleanField(verbose_name='principal')),
                ('entrega', models.BooleanField(verbose_name='entrega')),
                ('cobranca', models.BooleanField(verbose_name='cobran\xe7a')),
                ('correspondencia', models.BooleanField(verbose_name='correspond\xeancia')),
                ('cidade', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='production.Cidade', verbose_name='cidade')),
            ],
            options={
                'verbose_name': 'endere\xe7o',
                'verbose_name_plural': 'endere\xe7os',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(blank=True, max_length=2, verbose_name='s\xedgla')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('vagas', models.IntegerField(verbose_name='vagas')),
                ('data_inicio', models.DateTimeField(verbose_name='data de in\xedcio')),
                ('data_fim', models.DateTimeField(verbose_name='data de t\xe9rmino')),
                ('valor_inscricao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor de inscri\xe7\xe3o')),
                ('valor_grupo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor do grupo')),
                ('taxa_producao', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='taxa de produ\xe7\xe3o')),
                ('taxa_terapeuta', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='taxa do terapeuta')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='GrupoQuarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='c\xf3digo')),
                ('nome_en', models.CharField(blank=True, max_length=100, verbose_name='nome ingl\xeas')),
                ('nome_pt', models.CharField(max_length=100, verbose_name='nome portugu\xeas')),
                ('sigla2', models.CharField(blank=True, max_length=2, verbose_name='s\xedgla 2 d\xedgitos')),
                ('sigla3', models.CharField(blank=True, max_length=3, verbose_name='s\xedgla 3 d\xedgitoss')),
            ],
            options={
                'ordering': ['nome_pt'],
                'verbose_name': 'pa\xeds',
                'verbose_name_plural': 'pa\xedses',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('tipo', models.CharField(choices=[(b'F', 'F\xedsica'), (b'J', 'Jur\xeddica')], editable=False, max_length=1, verbose_name='tipo')),
                ('email', models.CharField(blank=True, max_length=250, verbose_name='email')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('site', models.CharField(blank=True, max_length=250, verbose_name='site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='codigo')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('capacidade', models.IntegerField(verbose_name='capacidade')),
                ('status', models.CharField(choices=[(b'L', b'Livre'), (b'O', b'Ocupado'), (b'I', b'Interditado'), (b'M', 'Manuten\xe7\xe3o'), (b'P', b'Parcialmente Ocupado')], default='L', max_length=1, verbose_name='situa\xe7\xe3o')),
                ('grupoquarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.GrupoQuarto', verbose_name='grupo de quarto')),
            ],
            options={
                'ordering': ['nome', 'grupoquarto'],
            },
        ),
        migrations.CreateModel(
            name='Salao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('capacidade', models.IntegerField(verbose_name='capacidade')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'sal\xe3o',
                'verbose_name_plural': 'sal\xf5es',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='production.Pessoa')),
                ('sobrenome', models.CharField(blank=True, max_length=150, null=True, verbose_name='sobrenome')),
                ('sannyas', models.CharField(blank=True, max_length=150, null=True, verbose_name='sannyas')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='RG')),
                ('orgao_rg', models.CharField(blank=True, max_length=25, null=True, verbose_name='org\xe3o RG')),
                ('data_emissao_rg', models.DateField(blank=True, null=True, verbose_name='data de emiss\xe3o RG')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('sexo', models.CharField(blank=True, choices=[(b'M', b'Masculino'), (b'F', b'Feminino')], max_length=1, null=True, verbose_name='sexo')),
                ('desde', models.DateField(blank=True, null=True, verbose_name='desde')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
            bases=('production.pessoa',),
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='production.Pessoa')),
                ('sobrenome', models.CharField(blank=True, max_length=150, null=True, verbose_name='sobrenome')),
                ('sannyas', models.CharField(blank=True, max_length=150, null=True, verbose_name='sannyas')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='RG')),
                ('orgao_rg', models.CharField(blank=True, max_length=25, null=True, verbose_name='org\xe3o RG')),
                ('data_emissao_rg', models.DateField(blank=True, null=True, verbose_name='data de emiss\xe3o RG')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('sexo', models.CharField(blank=True, choices=[(b'M', b'Masculino'), (b'F', b'Feminino')], max_length=1, null=True, verbose_name='sexo')),
            ],
            options={
                'abstract': False,
            },
            bases=('production.pessoa',),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Pais', verbose_name='pa\xeds'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='estado',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='production.Estado', verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='pais',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='production.Pais', verbose_name='pa\xeds'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Pessoa', verbose_name='pessoa'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Estado', verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='contato',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.Cliente', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='production.Cliente', verbose_name='cliente'),
        ),
    ]
