# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupoquarto',
            options={'ordering': ['nome'], 'verbose_name': 'Grupo de Quarto', 'verbose_name_plural': 'Grupos de Quartos'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='profiss\xe3o'),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='profissao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='profiss\xe3o'),
        ),
    ]
